In [122]:
import os
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
root_path = '/lfs/1/danfu/rekall_experiments/heartmri'
dev_folder = 'dev32'
test_folder = 'test32'
video_folder = 'flow_250_tp_AoV_bh_ePAT@c_MAG'
dev_labels_file = 'labels.csv'
test_labels_file = 'labels.csv'

In [ ]:
dev_labels_path = os.path.join(
    os.path.join(root_path, dev_folder),
    dev_labels_file
)
dev_labels = []
with open(dev_labels_path, 'r') as f:
    f.readline()
    for line in f.readlines():
        video_id, label = line.strip().split(',')
        dev_labels.append((video_id, int(label)))

In [ ]:
len([dv for dv in dev_labels if dv[1] == 1])

In [ ]:
test_labels_path = os.path.join(
    os.path.join(root_path, test_folder),
    test_labels_file
)
test_labels = []
with open(test_labels_path, 'r') as f:
    f.readline()
    for line in f.readlines():
        video_id, label = line.strip().split(',')
        test_labels.append((video_id, int(label)))

In [ ]:
len([tv for tv in test_labels if tv[1] == 0])

In [ ]:
patient_id = dev_labels[0][0]

In [ ]:
mri = np.load(os.path.join(
    os.path.join(
        os.path.join(root_path, dev_folder),
        video_folder
    ),
    '{}.npy'.format(patient_id)
))

In [ ]:
mri.shape

In [ ]:
mri[0]

In [ ]:
def montage(X): 
    count, m, n = X.shape
    nn = int(np.ceil(np.sqrt(count)))
    mm = nn
    M = np.zeros((mm * m, nn * n))

    image_id = 0
    for k in range(mm):
        for j in range(nn):
            if image_id >= count: 
                break
            sliceM, sliceN = j * m, k * n
            M[sliceN:sliceN + m, sliceM:sliceM + n] = X[image_id, :, :]
            image_id += 1
                               
    return M

In [ ]:
# Show negative examples
negatives_montaged = []
for patient_id, label in dev_labels:
    if label != 0:
        continue
    mri = np.load(os.path.join(
        os.path.join(
            os.path.join(root_path, dev_folder),
            video_folder
        ),
        '{}.npy'.format(patient_id)
    ))
    mri_montage = montage(mri)
    negatives_montaged.append(mri_montage)
#     plt.imshow(mri_montage, cmap='gray')
#     plt.show()
negatives_montaged = np.array(negatives_montaged)
negatives_montaged.shape

In [ ]:
plt.figure(figsize=(40,40))
plt.imshow(montage(negatives_montaged), cmap='gray')
plt.savefig('devs_negative_montaged.png')
plt.show()

In [ ]:
# Show positive examples
positives_montaged = []
for patient_id, label in dev_labels:
    if label != 1:
        continue
    mri = np.load(os.path.join(
        os.path.join(
            os.path.join(root_path, dev_folder),
            video_folder
        ),
        '{}.npy'.format(patient_id)
    ))
    mri_montage = montage(mri)
    positives_montaged.append(mri_montage)
#     plt.imshow(mri_montage, cmap='gray')
#     plt.show()
positives_montaged = np.array(positives_montaged)
positives_montaged.shape

In [ ]:
plt.figure(figsize=(10,10))
plt.imshow(montage(positives_montaged), cmap='gray')
plt.savefig('devs_positive_montaged.png')
plt.show()

# Explore other numpy files in random places

In [123]:
import numpy as np

In [126]:
filename = '/dfs/scratch0/paroma/heart-MRI/bav-classification/coral/6frames/6_brightest_coral_set_gamma_frame_list.npy'

In [127]:
arr = np.load(filename)

In [128]:
arr.shape

(27270, 2)

In [129]:
arr[0]

array([b'1001071', b'3'], dtype='|S7')

In [130]:
arr[:10]

array([[b'1001071', b'3'],
       [b'1001071', b'4'],
       [b'1001071', b'5'],
       [b'1001071', b'6'],
       [b'1001071', b'7'],
       [b'1001071', b'8'],
       [b'1002395', b'3'],
       [b'1002395', b'4'],
       [b'1002395', b'5'],
       [b'1002395', b'6']], dtype='|S7')

In [132]:
a = np.load('/dfs/scratch0/paroma/heart-MRI/bav-classification/coral/relative_marginals.npy')

In [134]:
import numpy as np
import matplotlib.pyplot as plt

# data_path = '/mnt/heart-MRI-Data/BAV/data/brightest/training_set/'
data_path = '/mnt/heart-MRI-Data/BAV/data/training_set/'
coral_path = data_path + 'coral_files/'
ids = np.load(data_path + "6_brightest_training_set_frame_labels.npy")
# ids = np.load(data_path + "6_brightest_training_set_patient_list.npy")
patient_labels = np.load(data_path + "6_brightest_training_set_patient_labels.npy")
marginals = np.load(coral_path+'marginals-106.npy')

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/heart-MRI-Data/BAV/data/training_set/6_brightest_training_set_frame_labels.npy'

In [139]:
a = np.load('/dfs/scratch0/paroma/heart-MRI/bav-classification/coral/gen_unknown_L_dev.npy')

In [140]:
a.shape

(5, 540)

In [142]:
b = np.load('/dfs/scratch0/paroma/heart-MRI/bav-classification/coral/gen_unknown_y_dev.npy')

In [143]:
b.shape

(540,)

In [145]:
a.shape

(5, 540)

In [147]:
b.shape

(540,)

In [150]:
b

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,  1.,  1.,
        1.,  1.,  1.,  1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1.,  1.,  1.,  1.,  1.,  1.,  1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1

In [156]:
b[24:30]

array([1., 1., 1., 1., 1., 1.])

In [148]:
a.T

array([[-1.,  1.,  0.,  0.,  1.],
       [-1.,  0.,  0.,  0., -1.],
       [-1.,  1.,  0.,  0., -1.],
       ...,
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.]])

In [157]:
a.T[:6]

array([[-1.,  1.,  0.,  0.,  1.],
       [-1.,  0.,  0.,  0., -1.],
       [-1.,  1.,  0.,  0., -1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  0., -1.,  1.],
       [ 0.,  1.,  0., -1.,  1.]])

In [158]:
a.T[24:30]

array([[-1., -1.,  0.,  0., -1.],
       [ 0.,  1.,  0.,  0., -1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  0.,  1.]])

In [159]:
np.where(b == 1)

(array([ 24,  25,  26,  27,  28,  29,  42,  43,  44,  45,  46,  47, 132,
        133, 134, 135, 136, 137, 216, 217, 218, 219, 220, 221, 258, 259,
        260, 261, 262, 263, 318, 319, 320, 321, 322, 323, 414, 415, 416,
        417, 418, 419]),)

In [160]:
a.T[42:48]

array([[-1.,  1.,  0., -1.,  1.],
       [-1.,  1.,  0.,  0.,  1.],
       [-1.,  1.,  0., -1.,  1.],
       [ 0.,  1.,  0., -1.,  1.],
       [ 1.,  1.,  1., -1.,  1.],
       [ 1.,  1.,  0., -1.,  1.]])

In [161]:
a.T[132:138]

array([[ 0., -1.,  0.,  0., -1.],
       [ 1.,  1.,  1.,  0., -1.],
       [ 1., -1.,  1.,  0., -1.],
       [ 1.,  1.,  1.,  0., -1.],
       [ 1.,  1.,  1.,  0., -1.],
       [ 1., -1.,  1.,  0., -1.]])

In [162]:
a.T[126:132]

array([[-1., -1.,  0., -1.,  1.],
       [-1., -1.,  0., -1.,  1.],
       [ 0.,  0.,  0., -1.,  1.],
       [ 0.,  1.,  0., -1.,  1.],
       [ 0.,  1.,  0., -1.,  1.],
       [ 0.,  1.,  0., -1.,  1.]])

In [163]:
from rekall import IntervalSetMapping, IntervalSet, Interval
from rekall.bounds import Bounds1D

ModuleNotFoundError: No module named 'rekall'